UPDATE imoveis_online
SET page_url = sd.page_url,
    descricao = sd.descricao,
    imgs = sd.imgs,
    endereco = sd.endereco,
    bairro = sd.bairro,
    additions = sd.additions,
    area_total = sd.area_total,
    area_util = sd.area_util,
    quartos = sd.quartos,
    idade_do_imovel = sd.idade_do_imovel,
    aluguel = sd.aluguel,
    condominio = sd.condominio,
    iptu = sd.iptu,
    latitude = sd.latitude,
    longitude = sd.longitude,
    vagas = sd.vagas,
    suites = sd.suites,
    banheiros = sd.banheiros,
    venda = sd.venda,
    temporada = sd.temporada,
    cidade = sd.cidade,
    last_update = sd.date_stored 
from imoveis_stage as sd
where imoveis_online.page_url = sd.page_url and (
    imoveis_online.descricao != sd.descricao or
    imoveis_online.imgs != sd.imgs or
    imoveis_online.endereco != sd.endereco or
    imoveis_online.bairro != sd.bairro or
    imoveis_online.additions != sd.additions or
    imoveis_online.area_total != sd.area_total or
    imoveis_online.area_util != sd.area_util or
    imoveis_online.quartos != sd.quartos or
    imoveis_online.idade_do_imovel != sd.idade_do_imovel or
    imoveis_online.aluguel != sd.aluguel or
    imoveis_online.condominio != sd.condominio or
    imoveis_online.iptu != sd.iptu or
    imoveis_online.latitude != sd.latitude or
    imoveis_online.longitude != sd.longitude or
    imoveis_online.vagas != sd.vagas or
    imoveis_online.suites != sd.suites or
    imoveis_online.banheiros != sd.banheiros or
    imoveis_online.venda != sd.venda or
    imoveis_online.temporada != sd.temporada or
    imoveis_online.cidade != sd.cidade )
