name: Moving airflow files

env:
  ACCOUNT: "github-deploy-gcf@rental-organizer.iam.gserviceaccount.com"

on:
  push:
    branches:
      - master
    # file paths to consider in the event. Optional; defaults to all.
    paths:
      - 'dags/load_data_into_sql/*'
      
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Deploy
      uses: actions-hub/gcloud@master
      env:
        PROJECT_ID: "rental-organizer"
        APPLICATION_CREDENTIALS: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS}}
      with:
          args: compute scp --impersonate-service-account=$ACCOUNT --recurse dags/* instance-4:/home/luizloureiro_alunos_utfpr_edu_br/airflow/dags  